### PR TITLE
Gemfile.lock was modified

### PR DESCRIPTION
**Pull request by RyanTG**
Here's the gemfile.lock. I don't understand what triggered the modification of this file. I had already added all the changed files, and then later in the game this one decided to be modified. 

As I mentioned in an email, the schema.rb file also decided to be modified. But that one appended ", using: :btree" to all the add_index lines. I don't know why. But I didn't commit it because it seems weird.

### CODE REVIEW

**Comment by scottwainstock** [comment]
I'm still having trouble getting this to work on my machine.. but I'm
sticking with it.

**Comment by RyanTG** [comment]
I wonder if it would work to just copy the contents from the source: https://github.com/xaviershay/enki/blob/master/Gemfile.lock

**Comment by scottwainstock** [comment]
That's a good idea, I'll give it a try.

**Comment by RyanTG** [comment]
Tell me if there's anything I can do. The problem is that the gemfile and gemfile.lock aren't matching?

**Comment by scottwainstock** [comment]
I'm just not able to type "bundle install" and have it work. I just end up
hitting a string of conflicts that I can't get past. Versions out of date
from other versions, etc...

**Comment by RyanTG** [comment]
I wish I could remember how I dealt with that. I had issues with bundle install, too. But they were mostly due to the version of ruby I was using vs the one specified in the gemfile. The errors didn't seem to be about gemfile.lock, and I'm not on my computer and can't access all my crazy SO searches for a solution. I feel like there was also a gem version conflict, but it was a simple one.

**Comment by RyanTG** [comment]
Any luck? I wonder if pulling from xaviershay/enki would help anything.

**Comment by scottwainstock** [comment]
I haven't had a chance to look at this again. I had family in town then I
had to go to NYC for work. I'll try again this weekend.

**Comment by RyanTG** [comment]
I didn't realize I had an open pull request on the blog (from 2015!). So, as a reminder: don't accept this request until the auth update is live (or, if you accept it, don't deploy it). I'll send a reminder when it's time.

**Comment by RyanTG** [comment]
And for good measure (hopefully not bad!) here are the other two files that git says I changed. Hopefully no bundle issues when you merge.

**Pull request merged**
